# Generated by Django 3.2.8 on 2021-11-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_categ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='categ',
            new_name='user',
        ),
    ]
